### ISSUE TITLE
Conflict with AMP extention

### ISSUE THREAD

**Issue by ch2856** [Hackwar/jlrouter#3] opened 2017-04-10 13:06 UTC
Hi Hannes. It's been a long 3 years :-)

I was testing the router and there is a conflict with AMP extension (google accelerated pages) from weeblr.com (same guys of sh404sef). If AMP is enabled I am getting 500 error. Maybe you should talk with them to understand where the conflict is.

Thanks,
Ram

**Comment by Hackwar** [comment] 2017-04-10 14:59
Can you make sure that the jlrouter plugin is the first in ordering? If that does not solve the issue, I will contact them.

**Comment by Hackwar** [comment] 2017-04-10 20:20
I found the issue. The wbamp extension loads the router even earlier than my plugin does and thus my plugin can't override the class. I will provide an update. It still requires to make sure that this plugin is first in calling order.

**Comment by ch2856** [comment] 2017-04-10 20:44
Thanks, 

I am still not in front of my PC (tested on a local server) so I couldn't check it out. By the way, from the short time I have tested it, it works just fine. I believe J team was wrong for not implanting it on 3.7. It's time for joomla to move on from past mistakes.

**Comment by Hackwar** [comment] 2017-04-12 20:36
The issue is fixed in the repo. I will deploy a new version with another feature soon. 😄

**Closed as completed by Hackwar** 2017-04-12 20:36 UTC

**Comment by ch2856** [comment] 2017-04-12 22:39
I am reopening it since now, the ID is not removed from article URL.
